version: '3'
services:
  app:
    container_name: nestjs_app
    restart: always
    image: d400800/nestjs_app:0.0.5
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    networks:
      - app-network
  mongo:
    image: mongo:5.0.3
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - './data/db:/data/db'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge