name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Building nestjs app
      run: npm run build

    - name: Log in to Docker Hub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        TIMESTAMP=$(date +%s)
        IMAGE_NAME=nestjs_app:$TIMESTAMP
        DOCKERHUB_REPO=${{ secrets.DOCKERHUB_USERNAME }}/nestjs_app:$TIMESTAMP
        
        # Build the Docker image
        docker build . --file Dockerfile --tag $IMAGE_NAME
        
        # Tag the Docker image
        docker tag $IMAGE_NAME $DOCKERHUB_REPO
        
        # Push the Docker image
        docker push $DOCKERHUB_REPO
